/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as WynagrodzeniaRouteImport } from './routes/wynagrodzenia'
import { Route as WydatkiRouteImport } from './routes/wydatki'
import { Route as SettingsRouteImport } from './routes/settings'
import { Route as LoginRouteImport } from './routes/login'
import { Route as KalkulatoryRouteImport } from './routes/kalkulatory'
import { Route as InviteRouteImport } from './routes/invite'
import { Route as AktywaRouteImport } from './routes/aktywa'
import { Route as IndexRouteImport } from './routes/index'

const WynagrodzeniaRoute = WynagrodzeniaRouteImport.update({
  id: '/wynagrodzenia',
  path: '/wynagrodzenia',
  getParentRoute: () => rootRouteImport,
} as any)
const WydatkiRoute = WydatkiRouteImport.update({
  id: '/wydatki',
  path: '/wydatki',
  getParentRoute: () => rootRouteImport,
} as any)
const SettingsRoute = SettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const KalkulatoryRoute = KalkulatoryRouteImport.update({
  id: '/kalkulatory',
  path: '/kalkulatory',
  getParentRoute: () => rootRouteImport,
} as any)
const InviteRoute = InviteRouteImport.update({
  id: '/invite',
  path: '/invite',
  getParentRoute: () => rootRouteImport,
} as any)
const AktywaRoute = AktywaRouteImport.update({
  id: '/aktywa',
  path: '/aktywa',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/aktywa': typeof AktywaRoute
  '/invite': typeof InviteRoute
  '/kalkulatory': typeof KalkulatoryRoute
  '/login': typeof LoginRoute
  '/settings': typeof SettingsRoute
  '/wydatki': typeof WydatkiRoute
  '/wynagrodzenia': typeof WynagrodzeniaRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/aktywa': typeof AktywaRoute
  '/invite': typeof InviteRoute
  '/kalkulatory': typeof KalkulatoryRoute
  '/login': typeof LoginRoute
  '/settings': typeof SettingsRoute
  '/wydatki': typeof WydatkiRoute
  '/wynagrodzenia': typeof WynagrodzeniaRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/aktywa': typeof AktywaRoute
  '/invite': typeof InviteRoute
  '/kalkulatory': typeof KalkulatoryRoute
  '/login': typeof LoginRoute
  '/settings': typeof SettingsRoute
  '/wydatki': typeof WydatkiRoute
  '/wynagrodzenia': typeof WynagrodzeniaRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/aktywa'
    | '/invite'
    | '/kalkulatory'
    | '/login'
    | '/settings'
    | '/wydatki'
    | '/wynagrodzenia'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/aktywa'
    | '/invite'
    | '/kalkulatory'
    | '/login'
    | '/settings'
    | '/wydatki'
    | '/wynagrodzenia'
  id:
    | '__root__'
    | '/'
    | '/aktywa'
    | '/invite'
    | '/kalkulatory'
    | '/login'
    | '/settings'
    | '/wydatki'
    | '/wynagrodzenia'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AktywaRoute: typeof AktywaRoute
  InviteRoute: typeof InviteRoute
  KalkulatoryRoute: typeof KalkulatoryRoute
  LoginRoute: typeof LoginRoute
  SettingsRoute: typeof SettingsRoute
  WydatkiRoute: typeof WydatkiRoute
  WynagrodzeniaRoute: typeof WynagrodzeniaRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/wynagrodzenia': {
      id: '/wynagrodzenia'
      path: '/wynagrodzenia'
      fullPath: '/wynagrodzenia'
      preLoaderRoute: typeof WynagrodzeniaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/wydatki': {
      id: '/wydatki'
      path: '/wydatki'
      fullPath: '/wydatki'
      preLoaderRoute: typeof WydatkiRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/settings': {
      id: '/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof SettingsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/kalkulatory': {
      id: '/kalkulatory'
      path: '/kalkulatory'
      fullPath: '/kalkulatory'
      preLoaderRoute: typeof KalkulatoryRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/invite': {
      id: '/invite'
      path: '/invite'
      fullPath: '/invite'
      preLoaderRoute: typeof InviteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/aktywa': {
      id: '/aktywa'
      path: '/aktywa'
      fullPath: '/aktywa'
      preLoaderRoute: typeof AktywaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AktywaRoute: AktywaRoute,
  InviteRoute: InviteRoute,
  KalkulatoryRoute: KalkulatoryRoute,
  LoginRoute: LoginRoute,
  SettingsRoute: SettingsRoute,
  WydatkiRoute: WydatkiRoute,
  WynagrodzeniaRoute: WynagrodzeniaRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
